### PR TITLE
Migrate to Kotlin Multiplatform and kotlinx.serialization

### LINKED ISSUE #7: Have you considered using kotlinx.serialization?
If you're not opposed, would you accept a pull request?

### PR DESCRIPTION
**Pull request by DSinge**
Hi, I work with @eygraber and this fixes #7. Sorry for the size of the changeset; a lot had to happen at the same time to get it working.

The only breaking change here should be using kotlinx.serialization instead of Jackson; the API shouldn't change other than that. We think the API can be improved by just using extension functions but that's a conversation for another day.

In the tests, we removed some of the tests that were testing Jackson specific behavior.

This is the initial port plus changes to gradle for KMP. Future plans are:
- make an abstraction around the JSON so that any JSON library can be used
- update some dependencies that currently have issues
- enable native KMP targets
- add static analysis tools to the project

We'll be using our own fork for now so there's pressure to get this merged.

### CODE REVIEW

**Comment by bestMechanic** [comment]
Any reason why this is not merged?

**Comment by eygraber** [comment]
We we're going to maintain a fork but our internal requirements changed and we delayed our need for the library. 

I'll try to schedule some free time to get that fork published to Maven Central.

**Comment by eygraber** [comment]
@codeniko any opposition to me making a new repo and artifact from this (I'd keep you in the copyright notice), or would you prefer this gets merged here?

**Comment by eygraber** [comment]
@bestMechanic we're going to maintain our own fork separately for now at https://github.com/eygraber/JsonPathKt

There's currently a snapshot at `com.eygraber:jsonpathkt:2.0.1-SNAPSHOT` (at the new maven central snapshot location).

**Pull request closed without merging**
